friend/urls.py
from django.conf.urls import url
from .views import index, add_friend


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-friend/', add_friend, name='add-friend'),
]

statistic/urls.py
from django.conf.urls import url
from .views import index


urlpatterns = [
    url(r'^$', index, name='index'),
]

status/urls.py
from django.conf.urls import url
from .views import index, add_status


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-status/', add_status, name='add-status'),
]

tugas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import friend.urls
import user_profile.urls
import status.urls
import statistic.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^friends/', include(friend.urls, namespace='friend')),
    url(r'^stats/', include(statistic.urls, namespace='stats')),
    url(r'^profile/', include(user_profile.urls, namespace='profile')),
    url(r'^', include(status.urls, namespace='status')),
]

user_profile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

friend/models.py
from django.db import models
from user_profile.models import UserProfile


# Create your models here.
class Friend(models.Model):
    name = models.CharField(max_length=255)
    photo_url = models.URLField(default="https://cdn.movemeback.com/movemeback/images/noprofile.png")
    profile_url = models.URLField()
    date_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(UserProfile, related_name="friends",
                             on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['-date_created']

statistic/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

status/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from user_profile.models import UserProfile

# Create your models here.
class Status(models.Model):
    status = models.TextField(max_length=350)
    user = models.ForeignKey(UserProfile, related_name="statuses", on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
 
    class Meta:
        ordering = ['-date_created']

user_profile/models.py
from django.db import models
import datetime

# Create your models here.
class UserProfile(models.Model):
    name = models.CharField(max_length=255)
    photo_url = models.URLField(default="https://avatars0.githubusercontent.com/u/22791949?v=4&s=400")
    birthday = models.DateField(default=datetime.date.today)
    gender = models.CharField(max_length=10)
    description = models.TextField()
    email = models.EmailField()

class Expertise(models.Model):
    user = models.ForeignKey(UserProfile, related_name="expertises", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

friend/forms.py
import http.client
from django.forms import ModelForm, ValidationError, CharField
from friend.models import Friend


def is_profile_url_valid(profile_url):
    if 'https://' in profile_url:
        profile_url = profile_url[8:]
    else:
        profile_url = profile_url[7:]

    try:
        req = http.client.HTTPConnection(profile_url)
        req.request("GET", "/")
        response = req.getresponse()
        return response.status == 200 or response.status == 301 or response.status == 302

    except Exception:
        raise ValidationError("Given page does not exist")


class FriendForm(ModelForm):

    photo_url = CharField(required=False)

    class Meta:
        model = Friend
        fields = ['name', 'profile_url', 'photo_url']

    def clean_profile_url(self):
        profile_url = self.cleaned_data['profile_url']
        if is_profile_url_valid(profile_url):
            return profile_url
        raise ValidationError("Given page does not exist")

    def clean_photo_url(self):
        return self.cleaned_data['photo_url'] or "https://cdn.movemeback.com/movemeback/images/noprofile.png"

status/forms.py
from django.forms import ModelForm
from status.models import Status

class Status_Form(ModelForm):
    class Meta:
        model = Status
        fields = ['status']

friend/views.py
import json
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from friend.forms import FriendForm
from user_profile.models import UserProfile


def index(request):

    friends = UserProfile.objects.first().friends.all()
    html = 'friend/friend.html'
    friend_form = FriendForm()

    response = {
        'friends': friends,
        'friend_form': friend_form,
    }

    error_json = request.GET.get('errors', None)

    if error_json is not None:
        errors = json.loads(error_json)
        response['errors'] = errors

    return render(request, html, response)


def add_friend(request):
    if request.method == 'POST':
        friend_form = FriendForm(request.POST)
        if friend_form.is_valid():
            friend = friend_form.save(commit=False)
            friend.user = UserProfile.objects.first()
            friend.save()

        else:
            return HttpResponseRedirect(reverse('friend:index') + '?errors=' +
                                        friend_form.errors.as_json())

    return HttpResponseRedirect(reverse('friend:index'))

statistic/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from status.models import Status
from friend.models import Friend
from user_profile.models import UserProfile

response = {}
def index(request):
    response['author'] = UserProfile.objects.first()

    feed = len(Status.objects.all())
    response['feed'] = feed

    friends = len(Friend.objects.all())
    response['friends'] = friends

    latest_post = Status.objects.first()
    response['latest_post'] = latest_post

    html = 'statistic/statistic.html'
    return render(request, html, response)

status/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Status
from user_profile.models import UserProfile
from .forms import Status_Form
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
response = {}
def index(request):
    status_list = Status.objects.all()
    html = 'status/status.html'
    paginator = Paginator(status_list, 15)
    page = request.GET.get('page')
    try:
        status = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        status = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        status = paginator.page(paginator.num_pages)
    response['status'] = status
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['status'] = request.POST['status']
        status = Status(status=response['status'],user=UserProfile.objects.first())
        status.save()
        messages.info(request, 'Your status has been posted successfully!')
        return HttpResponseRedirect('/')
    else:
        print(form.errors)
        return HttpResponseRedirect('/')

user_profile/views.py
from django.shortcuts import render
from user_profile.models import UserProfile

# Create your views here.
def index(request):
    profile = UserProfile.objects.first()
    expertises = profile.expertises.all()
    html = 'user_profile/user_profile.html'
    response = {
        'profile':profile,
        'expertises': expertises
    }
    return render(request, html, response)

friend/templates/friend/friend.html
{% extends "layout/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/friend.css' %}" />
<section name="input-friend" id="input-friend">
    <h2><b>Tambahkan Teman</b> <i class="fa fa-user-plus" aria-hidden="true"></i></h2><br>
    <form action="{% url 'friend:add-friend' %}" method="POST" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group {%if 'name' in errors %} has-error {% endif %}">
            <label class="col-sm-2 control-label">Nama</label>
            <div class="col-sm-10">
                <input class="form-control" type="text" placeholder="Albertus" name="name" maxlength="255" aria-describedby="helpBlockName" required id="id_name" >
            </div>
            {% if 'name' in errors %}
            {% for error in errors.name %}
            <div class="col-sm-10 col-sm-offset-2">
                <span id="helpBlockName" class="help-block">{{ error.message }}</span>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="form-group {%if 'profile_url' in errors %} has-error {% endif %}">
            <label class="col-sm-2 control-label">Profile URL</label>
            <div class="col-sm-10">
                <input type="url" class="form-control" placeholder="http://example.com" name="profile_url" maxlength="255" aria-describedby="helpBlockProfile" required id="id_profile_url" >
            </div>
            {% if 'profile_url' in errors %}
            {% for error in errors.profile_url %}
            <div class="col-sm-10 col-sm-offset-2">
                <span id="helpBlockProfile" class="help-block">{{ error.message }}</span>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="form-group {%if 'photo_url' in errors %} has-error {% endif %}">
            <label class="col-sm-2 control-label">Photo URL</label>
            <div class="col-sm-10">
                <input type="url" class="form-control" placeholder="Optional" name="photo_url" maxlength="255" aria-describedby="helpBlockPhoto" id="id_profile_url" >
            </div>
            {% if 'photo' in errors %}
            {% for error in errors.photo %}
            <div class="col-sm-10 col-sm-offset-2">
                <span id="helpBlockPhoto" class="help-block">{{ error.message }}</span>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <br>
        <div class="form-group submit-container">
            <div class="col-sm-12">
                <input class="btn btn-primary btn-lg round" id="submit" type="submit" value="Tambah" id="id_submit">
            </div>
        </div>
    </form>
</section>

<section name="list-friend" id="list-friend">
    <h2><b>Daftar Teman </b><i class="fa fa-address-card-o" aria-hidden="true"></i></h2>
    <div class="card-list">
        {% for friend in friends %}
        <div class="card-container">
            <div class="card">
                <img width=100 height=100 class="profile-picture" src="{{ friend.photo_url }}" width=/>
                <div class="card-details">
                    <p>{{ friend.name }}</p>
                    <p>{{ friend.date_created|date:"d M Y H:i:s" }}</p>
                    <p><a href="{{ friend.profile_url }}">Profil</a></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

statistic/templates/statistic/statistic.html
{% extends "layout/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/statistic.css' %}" />

<section id = "statssec">
<h1><b>Statistic </b><i class="fa fa-bar-chart" aria-hidden="true"></i></h1>

<div class="identity">
    <img class="img-circle profile-pic" src="{{ author.photo_url }}"/>
    <h3 class="profile-name"><b>{{ author.name }}</b></h3>
</div>

<section name="stats" id="stats">
    <div class="contain-numbers">
        <div class="container friends">
            <div class="stats" id="friends-stat">
                <strong>Friends</strong> <i class="fa fa-users" aria-hidden="true"></i><br> {{ friends }} People
            </div>
        </div>
        <div class="container feeds">
            <div class="stats" id="feeds-stat">
                <strong>Feed</strong> <i class="fa fa-rss" aria-hidden="true"></i><br> {{ feed }} Post
            </div>
        </div>
    </div>
</section>
</section>

<section name="latest-post" id="latest-post">
    <div class="last-post-head"><strong>What did {{ author.name }} last say?</strong></div>

    {% if feed %}
    <div class="container" id="last-post">
        <div class="identity post-identity">
            <img class="img-circle post-pic" src="{{ author.photo_url }}"/>
            <p class="post-name" ><strong>{{ author.name }}</strong></p>
        </div>
        <div class="post-status">
            {{ latest_post.status |linebreaksbr }}
        </div>
        <div class="post-date">
            {{ latest_post.date_created }}
        </div>
    </div>
    {% else %}
    <div class="no-posts">
        <p>{{author.name }} hasn't posted anything yet :(</p>
        <p>Go on and <a href=""><strong>post something!</strong></a></p>
    </div>
    {% endif %}
</section>

{% endblock %}

status/templates/status/status.html
 {% extends "layout/base.html" %}
 {% load static %}
 {% block content %}
 <link rel="stylesheet" type="text/css" href="{% static 'css/status.css' %}" />
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

 <section name="input-status" id="input-status">
   <div class="container2">
     {% if messages %}
     <ul id="myAlert" class="alert alert-success animated zoomIn" role="alert">
        {% for message in messages %}
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    </ul>
    {% endif %}
    <form action="{% url 'status:add-status' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            <label style="font-size: 30px">Update Status <i class="fa fa-comment-o" aria-hidden="true"></i></label>
            <textarea id="text-content" type="text" class="form-control" name="status" rows="4" placeholder="Enter status here" onKeyup="count_remaining_character()" data-emojiable="true"></textarea>
            <div id="character-count" align="right">350</div>
            <input class="btn btn-primary btn-lg round" id="submit" type="submit" value="Post" id="id_submit">
        </div>
    </form>
</div>
</section>




<section name="my-list" id="my-list">
    <div class="container2">
       <div class="flex">
        {% for data in status %}
        {% if messages and forloop.first %}
        <div class="flex-item animated fadeInDown">
            {% else %}
            <div class="flex-item">
                {% endif %}
                <div class="list-status">
                    <div class="list-status-photo-status">
                        <img class = "img-circle" id="status-photo" src="{{data.user.photo_url}}" style="width:50px;">
                        <b id="status-name"> {{data.user.name}} </b>
                    </div>
                    <div class="list-status-status">
                        {{data.status|linebreaksbr}}
                    </div>
                    <div class="list-status-date">
                        {{data.date_created | date:"d M Y H:i:s"}}
                    </div>
                </div>
            </div>

            {% endfor %}
            <div align="center">
                <div class="pagination">
                    <li >
                        {% if status.has_previous %}
                        <a href="?page={{ status.previous_page_number }}" >previous</a>
                        {% endif %}
                    </li>
                    <li >
                        {% if status.has_next %}
                        <a href="?page={{ status.next_page_number }}" >next</a>
                        {% endif %}
                    </li>
                </div>
                <div class="current" align="center">
                    Page {{ status.number }} of {{ status.paginator.num_pages }}
                </div>
            </div>
        </div>
    </div>
</div>
</section>

<script type="application/javascript">
function count_remaining_character() {
    var max_length = 350;
    var character_entered = $('#text-content').val().length;
    var character_remaining = max_length - character_entered;
    $('#character-count').html(character_remaining);
    if(max_length < character_entered) {
        $('#character-count').css('color','#FF0000');
    } else {
        $('#character-count').css('color','#A0A0A0');
    }
}
</script>



{% endblock %}        

templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="tugassatuasik">
    <meta name="author" content="{{author}}">

    <!-- Favicon -->
    <link rel="shortcut icon" href="http://www.iconj.com/ico/j/j/jjw112xktj.ico" type="image/x-icon" />
    <!-- bootstrap css -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.3.0/css/roboto.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.3.0/css/material-fullpalette.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.3.0/css/ripples.min.css">
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/emoji-picker/1.1.5/css/emoji.css" rel="stylesheet">
    

    <title>
        {% block title %} Tugas Satu Asik  {% endblock %}
    </title>
</head>


<body>
    <header >
        {% include "partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
            <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer class="footer">
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.3.0/js/material.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.3.0/js/ripples.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/emoji-picker/1.1.5/js/config.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/emoji-picker/1.1.5/js/util.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/emoji-picker/1.1.5/js/jquery.emojiarea.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/emoji-picker/1.1.5/js/emoji-picker.js"></script>
    

</body>
</html>

templates/partials/footer.html
<style type="text/css">
html {
  position: relative;
  min-height: 100%;
}
body {
  /* Margin bottom by footer height */
  margin-bottom: 100px;
}
.footer {

  position: absolute;
  bottom: 0;
  width: 100%;
  /* Set the fixed height of the footer here */
  height: 70px;
  line-height: 60px; /* Vertically center the text there */
  background-color: #394948;
  color: #ffffff;
}

.resize-container {
  position: relative;
  display: inline-block;
  cursor: move;
  margin: 0 auto;
}

.resize-container img {
  display: block
}

.resize-container:hover img,
.resize-container:active img {
  outline: 2px dashed rgba(222,60,80,.9);
}   

</style>

<div class="container" style="text-align: center; font-size: 12px;">
	<span >Made with <span style="color: #fd0864">💔</span> and <span style="color: #fff000">&#128557;</span> by <a href="https://gitlab.com/ppw2017A-6/tugassatuasik">Norman Ganteng and the gengs</a> 
</div>

templates/partials/header.html
<style>
ul.nav a:hover { color: #fff !important; }

nav ul {
  list-style: none;
  text-align: center;
}
nav ul li {
  display: inline-block;
}
nav ul li a {
  display: block;
  padding: 15px;
  text-decoration: none;
  color: #aaa;
  font-weight: 800;
  text-transform: uppercase;
  margin: 0 10px;
}
nav ul li a,
nav ul li a:after,
nav ul li a:before {
  transition: all .5s;
}
nav ul li a:hover {
  color: #555;
}

/* SHIFT */
nav.shift ul li a {
  position:relative;
  z-index: 1;
}
nav.shift ul li a:hover {
  color: #91640F;
}
nav.shift ul li a:after {
  display: block;
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  margin: auto;
  width: 100%;
  height: 1px;
  content: '.';
  color: transparent;
  background: #F1C40F;
  visibility: none;
  opacity: 0;
  z-index: -1;
}
nav.shift ul li a:hover:after {
  opacity: 1;
  visibility: visible;
  height: 100%;
}



/* Keyframes */
@-webkit-keyframes fill {
  0% {
    width: 0%;
    height: 1px;
  }
  50% {
    width: 100%;
    height: 1px;
  }
  100% {
    width: 100%;
    height: 100%;
    background: #333;
  }
}

/* Keyframes */
@-webkit-keyframes circle {
  0% {
    width: 1px;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    margin: auto;
    height: 1px;
    z-index: -1;
    background: #eee;
    border-radius: 100%;
  }
  100% {
    background: #aaa;
    height: 5000%;
    width: 5000%;
    z-index: -1;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    margin: auto;
    border-radius: 0;
  }
}

}
</style>
<nav class="shift navbar bg-default scrolling-navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'status:index' %}"><img src="https://preview.ibb.co/nqk6RG/Tugas_Satu_Asik.png" alt="Tugas_Satu_Asik" border="0" height="40px" height="auto"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav shift">
        <li><a href="{% url 'status:index' %}"><i class="fa fa-comment-o" aria-hidden="true"></i> Status</a></li>
        <li><a href="{% url 'profile:index' %}"><i class="fa fa-user-circle" aria-hidden="true"></i> Profile</a> </li>
        <li><a href="{% url 'friend:index' %}"><i class="fa fa-address-book-o" aria-hidden="true"></i> Friends</a> </li>
        <li><a href="{% url 'stats:index' %}"><i class="fa fa-bar-chart" aria-hidden="true"></i> Stats</a> </li>
      </ul>
    </div>
  </div>
</nav>

<script>
	$('#navbar li').click(function() {
    $(this).addClass('active').siblings('li').removeClass('active');
});
</script>

user_profile/templates/user_profile/user_profile.html
{% extends "layout/base.html" %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/user_profile.css' %}" />
<section>
	<div class="container2">
		<h1 style="margin-left: 20px"><b>Profile <i class="fa fa-user-circle-o" aria-hidden="true"></i></b></h1>
		<center>
			<img class="circular--square" src="{{profile.photo_url}}" height="250" width="250" style="margin-bottom: 20px;">
		</center>
		<center>
			<p><b><font size="6">{{profile.name}} </font></b></p>
		</center>
	</div>
</section>
<section name="data-profile" id="data-profile">
    <div >
			<table align="center">
				<tr> <td><b>Birthday</b></td> <td>{{profile.birthday}}</td> </tr>
				<tr> <td><b>Gender</b></td> <td>{{profile.gender}}</td> </tr>
				<tr> <td><b>Expertise</b></td> <td>{% for expertise in expertises %} <span class="label label-default">{{ expertise.name }}</span>  {% endfor %}</td> </tr>
				<tr> <td><b>Description</b></td> <td>{{profile.description}}</td> </tr>
				<tr> <td><b>Email</b></td> <td>{{profile.email}}</td> </tr>
			</table>
    </div>
</section>
{% endblock %}